version: '2'
services:
  lib:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NODE_VERSION: "12-stretch"
    working_dir: /opt/app
    environment:
      - CHROME_BIN=/usr/bin/chromium
    entrypoint: yarn
    command:
      - run
      - watch
