#!/bin/bash
set -e

function usage() {
    echo -n \
    "Usage: $(basename "$0")
    Builld vagrant VM."
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # run vagrant from up one directory relative to this script
        cd "$(dirname "$0")/.."
        vagrant up --provision
        vagrant ssh -c "cd /vagrant && ./scripts/update"
    fi
fi
